plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'AI-Budget-Manager'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.oracle.database.jdbc:ojdbc11'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
	if (file(".env").exists()) {
		file(".env").readLines().each {
			if (!it.isEmpty() && !it.startsWith("#")) {
				def pos = it.indexOf("=")
				if (pos > 0) {
					def key = it.substring(0, pos).trim()
					def val = it.substring(pos + 1).trim()
					if (val.startsWith("\"") && val.endsWith("\"")) {
						val = val.substring(1, val.length() - 1)
					} else if (val.startsWith("'") && val.endsWith("'")) {
						val = val.substring(1, val.length() - 1)
					}
					environment key, val
				}
			}
		}
	}
}

bootRun {
	if (file(".env").exists()) {
		file(".env").readLines().each {
			if (!it.isEmpty() && !it.startsWith("#")) {
				def pos = it.indexOf("=")
				if (pos > 0) {
					def key = it.substring(0, pos).trim()
					def val = it.substring(pos + 1).trim()
					if (val.startsWith("\"") && val.endsWith("\"")) {
						val = val.substring(1, val.length() - 1)
					} else if (val.startsWith("'") && val.endsWith("'")) {
						val = val.substring(1, val.length() - 1)
					}
					environment key, val
				}
			}
		}
	}
}

